name: Build app
run-name: ${{ github.actor }} is building the app with GitHub Actions ğŸš€
on:
  push:
    branches:
      - deploy_this_branch_to_digital_ocean
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Build with npm
        uses: ankitasen-ubmainz/build-npm-action@v0.2
      - run: echo "ğŸ Build and Test status is ${{ job.status }}."
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: dbd_randomizer_ui
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: echo "ğŸ Deployment to digitalocean status is ${{ job.status }}."
